//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seat2Gether.Reports {
    
    
    public partial class Seat2GetherReports {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        /// <summary>
        /// Seat2GetherReportsViewer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.Reporting.WebForms.ReportViewer Seat2GetherReportsViewer;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_A_BBNR_Bemerkungen_Zuschnitt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_A_BBNR_Bemerkungen_Zuschnitt;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_A_BBNr_Gurtschloss_Wandseitig control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_A_BBNr_Gurtschloss_Wandseitig;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_T_Auftrag_Bemerkungen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_T_Auftrag_Bemerkungen;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_A_BBNr_Sesselblenden_Zusatzangaben control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_A_BBNr_Sesselblenden_Zusatzangaben;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_A_BBNr_Sesselblenden_Blockierungen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_A_BBNr_Sesselblenden_Blockierungen;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_TGR_Zunschnitt_BA_TG control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_TGR_Zunschnitt_BA_TG;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_A_BBnr_Bemerkungen_Sonderstuhl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_A_BBnr_Bemerkungen_Sonderstuhl;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_UA_Kinostuhl_45 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_UA_Kinostuhl_45;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_UA_Anbauteile_MOntage_FondUD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_UA_Anbauteile_MOntage_FondUD;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_UA_Anbauteile_MOntage_FondOD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_UA_Anbauteile_MOntage_FondOD;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_UA_Anbauteile_MOntage_Fond control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_UA_Anbauteile_MOntage_Fond;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_A_BBnr_Bemerkungen_Montage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_A_BBnr_Bemerkungen_Montage;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_UA_Schiebestuhl_44 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_UA_Schiebestuhl_44;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_UA_KSW_Sonderstuhl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_UA_KSW_Sonderstuhl;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_UA_KSW_Montage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_UA_KSW_Montage;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_UA_Anbauteile_MOntage_NONFondUD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_UA_Anbauteile_MOntage_NONFondUD;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_UA_Anbauteile_MOntage_NONFondOD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_UA_Anbauteile_MOntage_NONFondOD;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_UA_Anbauteile_MOntage_NONFondNoDeck control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_UA_Anbauteile_MOntage_NONFondNoDeck;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_UA_Fahrerstuhl_Stückliste control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_UA_Fahrerstuhl_Stückliste;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_UA_Fahrerstuhl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_UA_Fahrerstuhl;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_UA_KSW_Näherei control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_UA_KSW_Näherei;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_TGR_Vorhang control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_TGR_Vorhang;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_UA_Fahrernebenstuhl_Stückliste control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_UA_Fahrernebenstuhl_Stückliste;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_Anbauteile_Zuschnitt_Kissen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_Anbauteile_Zuschnitt_Kissen;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_A_BBnr_Bemerkungen_Näherei control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_A_BBnr_Bemerkungen_Näherei;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_A_BBNr_Anzahl_Rücken control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_A_BBNr_Anzahl_Rücken;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_A_BBNR_Gessler_gruppiert control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_A_BBNR_Gessler_gruppiert;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_Anbauteile_Zuschnitt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_Anbauteile_Zuschnitt;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_UA_49 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_UA_49;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_UA_43 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_UA_43;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_UA_Divers_98 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_UA_Divers_98;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_Bemerkungen_Zuschnitt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_Bemerkungen_Zuschnitt;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_UA_KSW_Zuschnitt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_UA_KSW_Zuschnitt;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_UA_Diverses control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_UA_Diverses;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_UA_Fahrernebenstuhl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_UA_Fahrernebenstuhl;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_Anbauteile_Zuschnitt_Rücken control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_Anbauteile_Zuschnitt_Rücken;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_TGR_Zuschnitt_BA_TG control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_TGR_Zuschnitt_BA_TG;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_UA_23 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_UA_23;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_T_ST_Variante_Stoffangabe control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_T_ST_Variante_Stoffangabe;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_SP_BBNR_Stammdaten control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_SP_BBNR_Stammdaten;
        
        /// <summary>
        /// Seat2GetherReportsDataSource_A_BBNR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource Seat2GetherReportsDataSource_A_BBNR;
    }
}
